# Generated by Django 5.2.4 on 2025-08-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название точки (необязательно)')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес заведения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Адрес заведения',
                'verbose_name_plural': 'Адреса заведений',
                'ordering': ['id'],
            },
        ),
    ]
