# Generated by Django 5.2.1 on 2025-08-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotions',
            old_name='description',
            new_name='redText',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='promotions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Картинка'),
        ),
    ]
