# Generated by Django 5.2.4 on 2025-08-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_slug_promotions_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_type', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
