# Generated by Django 5.2.4 on 2025-08-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
