# Generated by Django 5.2.4 on 2025-08-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_promotions_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='time_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
