# Generated by Django 5.2.4 on 2025-08-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_drop_delivery_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], default='delivery', max_length=20, verbose_name='Способ получения'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Оплата картой'), ('afterpay', 'Оплата при получении')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
