# Generated by Django 5.2.4 on 2025-08-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_method_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии и время'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('confirmed', 'Подтвержденный'), ('in_progress', 'В обработке'), ('ready', 'Готов к выдаче'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=20),
        ),
    ]
