# Generated by Django 5.2.4 on 2025-08-15 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0004_alter_order_comments_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.location', verbose_name='Адрес заведения (для самовывоза)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержденный'), ('in_progress', 'В обработке'), ('ready', 'Готов к выдаче'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=20),
        ),
    ]
