# Generated by Django 5.2.4 on 2025-08-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Оплата картой (Переводом)'), ('afterpay', 'Оплата наличными')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
