# Generated by Django 5.2.4 on 2025-08-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_payment_id_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('confirmed', 'Подтвержденный'), ('in_progress', 'В обработке'), ('ready', 'Готов к выдаче'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=20),
        ),
    ]
