# Generated by Django 5.2.4 on 2025-08-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_dish_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Изображение для описании'),
        ),
    ]
