# Generated by Django 5.2.4 on 2025-08-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_dish_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
